import { expect } from "chai";
import { loadFixture } from "@nomicfoundation/hardhat-network-helpers";
import { viem } from "hardhat";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { type Address, type WalletClient, type PublicClient, getAddress } from "viem";

// Helper function to sign xp messages
async function signAddXP(
  server: WalletClient,
  xp: any, // Contract instance from hre.viem.deployContract
  publicClient: PublicClient,
  nftAddr: Address,
  tokenId: bigint,
  amount: bigint
) {
  // EIP-712 typed data structure
  const domain = {
    name: "XP",
    version: "1.0",
    chainId: await publicClient.getChainId(),
    verifyingContract: xp.address,
  };
  const types = {
    addXP: [
      { name: "nftAddr", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "nonce", type: "uint256" },
    ],
  };
  const nonce = await xp.read.nonces([nftAddr, tokenId]);
  const message = {
    nftAddr,
    tokenId,
    amount,
    nonce,
  };

  return await server.signTypedData({
    account: server.account!,
    domain,
    types,
    primaryType: "addXP",
    message,
  });
}

describe("XP", function () {
  async function deployXPFixture() {
    const [owner] = await viem.getWalletClients();
    const publicClient = await viem.getPublicClient();

    // Deploy XP
    const xp = await viem.deployContract("XP", [
      owner.account!.address,
      owner.account!.address, // Server address (for testing, set to owner)
    ]);

    return {
      xp,
      owner,
      publicClient,
    };
  }

  describe("Deployment", function () {
    it("Should set the right owner and server for the XP contract", async function () {
      const { xp, owner } = await loadFixture(deployXPFixture);

      expect((await xp.read.owner()).toLowerCase()).to.equal(
        owner.account!.address
      );
      expect((await xp.read.server()).toLowerCase()).to.equal(
        owner.account!.address
      );
    });
  });

  describe("Server", function () {
    it("Should set up a new server if called by owner", async function () {
      const { xp } = await loadFixture(deployXPFixture);

      // Create a new random wallet to be the new server
      const randomPrivateKey = generatePrivateKey();
      const newServerAccount = privateKeyToAccount(randomPrivateKey);

      // Set the new server
      await xp.write.setServer([newServerAccount.address]);

      // Verify the server was changed
      expect(await xp.read.server()).to.equal(newServerAccount.address);
    });

    it("Should fail to set up a new server if called by non-owner", async function () {
      const { xp, owner } = await loadFixture(deployXPFixture);

      // Create a new random wallet to be the new server
      const randomPrivateKey = generatePrivateKey();
      const newServerAccount = privateKeyToAccount(randomPrivateKey);

      // Set the new server from a non-owner account
      await expect(
        xp.write.setServer([newServerAccount.address], { account: newServerAccount })
      ).to.be.rejected;

      // Verify the server wasn't changed
      expect(await xp.read.server()).to.equal(getAddress(owner.account!.address));
    });
  });

  describe("Usage", function () {
    it("Should sign an amount and update the balance of the right nft", async function () {
      const { xp, owner, publicClient } = await loadFixture(deployXPFixture);

      const nftAddr: Address = "0x1234567890123456789012345678901234567890"; // Example NFT address
      const tokenId = 1n;
      const amount = 101n;
      const nonce = await xp.read.nonces([nftAddr, tokenId]);

      const signature = await signAddXP(
        owner,
        xp,
        publicClient,
        nftAddr,
        tokenId,
        amount
      );

      // Check initial balance - 0
      expect(await xp.read.balances([nftAddr, tokenId])).to.equal(0n);

      // Call addXP with the signature
      await xp.write.addXP([nftAddr, tokenId, amount, nonce, signature]);

      // Check updated balance
      expect(await xp.read.balances([nftAddr, tokenId])).to.equal(amount);
    });

    it("Should fail to update balance with an invalid signature not generated by server", async function () {
      const { xp, owner, publicClient } = await loadFixture(deployXPFixture);

      const nftAddr: Address = "0x1234567890123456789012345678901234567890"; // Example NFT address
      const tokenId = 1n;
      const amount = 101n;
      const nonce = await xp.read.nonces([nftAddr, tokenId]);

      // Create a different wallet to sign the message (invalid signer)
      const randomPrivateKey = generatePrivateKey();
      const invalidSigner = privateKeyToAccount(randomPrivateKey);
      const signature = await signAddXP(
        { ...owner, account: invalidSigner },
        xp,
        publicClient,
        nftAddr,
        tokenId,
        amount
      );

      // Attempt to call addXP with the invalid signature
      await expect(
        xp.write.addXP([nftAddr, tokenId, amount, nonce, signature])
      ).to.be.rejected;

      // Check that balance is still 0
      expect(await xp.read.balances([nftAddr, tokenId])).to.equal(0n);
    });
  });
});
